openapi: "3.0"
info:
  title: PyBloods
  version: 0.1.0
paths:
  /observations:
    get:
      summary: Return a list of all observations
      responses:
        200:
          description: A successlisting of all observations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Observation"
  /units:
    get:
      summary: Return a list of all available units
      responses:
        200:
          description: A successful listing of all units
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Unit"
  /samples:
    get:
      summary: Return a list of all available samples
      responses:
        200:
          description: |
            A collection of all bloods reports. This is usually
            a group of one or more results (eg, blood chemistry, endocrinology, etc)
            takes from a single vial of blood.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sample"
  /sources:
    get:
      summary: Return a list of all available sources
      responses:
        200:
          description: A collection of laboratories and their healthcare providers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Source"
  /providers:
    get:
      summary: Return a list of all available healthcare providers
      responses:
        200:
          description: A collection of healthcare providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Provider"
  /note_groups:
    get:
      summary: Return a list of all available note groups
      responses:
        200:
          description: A collection of collection of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NoteGroup"
  /note_group/{id}:
    get:
      summary: Return a list of notes
      responses:
        200:
          description: A collection of notes
          content:
            application/json:
              schema:
                type: object
                properties:
                  note_group_id:
                    type: integer
                    format: inte64
                  notes:
                    type: array
                    items: $ref: "#/components/schemas/Note"

components:
  schemas:
    NoteGroup:
      required:
        - note_group_id
      properties:
        note_group_id:
          type: integer
          format: int64
    Note:
      allOf:
        - $ref: "#/components/schemas/NewNote"
        - required:
            - note_id
          properties:
            note_id:
              type: integer
              format: int64
    NewNote:
      required:
        - note_group_id
        - language
        - documents
        - content
      properties:
        note_group_id:
          type: integer
          format: int64
        language:
          type: string
        documents:
          type: array
          items:
            type: string
    Provider:
      allOf:
        - $ref: "#/components/schemas/NewProvider"
        - required:
            - provider_id
          properties:
            provider_id:
              type: integer
              format: int64
    NewProvider:
      required:
        - name
      properties:
        name:
          type: string
    Source:
      allOf:
        - $ref: "#/components/schemas/NewSource"
        - required:
            - source_id
          properties:
            source_id:
              type: integer
              format: int64
    NewSource:
      required:
        - provider_id
        - lab_id
      properties:
        provider_id:
          type: integer
          format: int64
        lab_id:
          type: integer
          format: int64
    Sample:
      allOf:
        - $ref: "#/components/schemas/NewSample"
        - required:
            - sample_id
          properties:
            sample_id:
              type: integer
              format: int64
    NewSample:
      required:
        - taken_at
        - source_id
      properties:
        taken_at:
          type: string
          format: 'date-time'
        source_id:
          type: integer
          format: int64
    Observation:
      allOf:
        - $ref: "#/components/schemas/NewObservation"
        - required:
            - observation_id
          properties:
            observation_id:
              type: integer
              format: int64
    NewObservation:
      required:
        - value
        - unit_id
        - recorded_at
      properties:
        value:
          type: number
          format: double
        unit_id:
          type: integer
          format: int64
        extracted_at:
          type: string
          format: 'date-time'
        processed_at:
          type: string
          format: 'date-time'
    Unit:
      allOf:
        - $ref: "#/components/schemas/NewUnit"
        - required:
            - unit_id
          properties:
            unit_id:
              type: integer
              format: int64
    NewUnit:
      required:
        - name
      properties:
        name:
          type: string
